# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_destorior.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(186, 188)
        self.start_btn = QtWidgets.QPushButton(dialog)
        self.start_btn.setGeometry(QtCore.QRect(100, 160, 81, 23))
        self.start_btn.setObjectName("start_btn")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(dialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.start_btn)
        self.stop_btn = QtWidgets.QPushButton(dialog)
        self.stop_btn.setGeometry(QtCore.QRect(10, 160, 81, 23))
        self.stop_btn.setObjectName("stop_btn")
        self.buttonGroup_2.addButton(self.stop_btn)
        self.textBrowser = QtWidgets.QTextBrowser(dialog)
        self.textBrowser.setGeometry(QtCore.QRect(0, 10, 191, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.input = QtWidgets.QComboBox(dialog)
        self.input.setGeometry(QtCore.QRect(0, 50, 191, 22))
        self.input.setObjectName("input")
        self.language = QtWidgets.QComboBox(dialog)
        self.language.setGeometry(QtCore.QRect(0, 90, 191, 22))
        self.language.setObjectName("language")
        self.mic = QtWidgets.QSlider(dialog)
        self.mic.setGeometry(QtCore.QRect(10, 120, 160, 22))
        self.mic.setOrientation(QtCore.Qt.Horizontal)
        self.mic.setObjectName("mic")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.start_btn.setText(_translate("dialog", "開始"))
        self.stop_btn.setText(_translate("dialog", "結束"))
        self.textBrowser.setHtml(_translate("dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">喵嗚遊戲破壞者</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())
